import Navigation from "./components/Navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex md:p-10 p-5 flex-col md:flex-row md:items-start">
          <Navigation />
          <div id="content" className="w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
